### ISSUE TITLE
Table name not using namespace

### ISSUE THREAD

**Issue by sharq1** [spree-contrib/spree_comments#50]
`spree_comments` table is created as `comments` and then renamed to `spree_comments`, so if the `comments` table already existed it will effectively be removed (inaccessible). In case of our app we noticed that only after receiving NewRelic alert about dozens of exceptions in production app.

**Comment by reinaris** [comment]
there is a migration which prefixes the comments tables with spree: https://github.com/spree-contrib/spree_comments/blob/master/db/migrate/20111123200847_prefix_tables_with_spree.rb

**Comment by JDutil** [comment]
You could merge the migrations into a single migration that creates the table with the namespace right off the bat if you'd like. PR welcome.
